# Generated by Django 5.0.9 on 2024-10-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0044_circuit_groups'),
        ('dcim', '0191_module_bay_rebuild'),
        ('mobile', '0002_alter_mobiledevice_tenant'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_number_set', to='dcim.sitegroup'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_number_set', to='tenancy.contact'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_number_set', to='mobile.mobiledevice'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_number_set', to='circuits.provider'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_number_set', to='dcim.region'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_number_set', to='tenancy.tenant'),
        ),
    ]
