# Generated by Django 5.0.9 on 2024-10-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_mobilenumber_group_alter_mobilenumber_contact_and_more'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_device_set', to='tenancy.tenantgroup'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_number_set', to='tenancy.tenantgroup'),
        ),
    ]
