# Generated by Django 5.0.9 on 2024-10-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_mobiledevice_group_alter_mobilenumber_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiledevice',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mobilenumber',
            name='group',
        ),
    ]
