# Generated by Django 5.0.9 on 2024-10-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_remove_mobiledevice_group_remove_mobilenumber_group'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_device_set', to='tenancy.contact'),
        ),
    ]
